'use client';
import Link from 'next/link';
import {useState,useEffect,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {collections,collectionItemHref} from '@/config/collections';
import {Icon} from '@/components/commerce/Icon';
import {readCart} from '@/lib/commerce';
export function Header(){const [open,setOpen]=useState('');const [rail,setRail]=useState(false);const [count,setCount]=useState(0);const [query,setQuery]=useState('');const router=useRouter();const ref=useRef<HTMLElement>(null);
useEffect(()=>{const update=()=>setCount(readCart().reduce((n,x)=>n+x.quantity,0));update();window.addEventListener('plant-shop-cart-updated',update);const close=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node)){setOpen('');setRail(false)}};document.addEventListener('pointerdown',close);return()=>{window.removeEventListener('plant-shop-cart-updated',update);document.removeEventListener('pointerdown',close)}},[]);
return <header className="ps-header" ref={ref} onKeyDown={e=>{if(e.key==='Escape'){setOpen('');setRail(false)}}}><div className="ps-top"><span>Một chút xanh. Một ngày khác.</span><Link href="/huong-dan">Hướng dẫn mua hàng ↗</Link><Link href="/xem-truoc/flash-sale">Thiết lập flash sale</Link></div><div className="ps-brandbar ps-wrap"><Link className="ps-logo" href="/" aria-label="Plant Shop trang chủ"><Icon name="leaf" size={32}/>plant<span>shop.</span></Link><form className="ps-search" onSubmit={e=>{e.preventDefault();router.push('/cua-hang?q='+encodeURIComponent(query));setOpen('');setRail(false)}}><Icon name="search"/><input aria-label="Tìm sản phẩm" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bạn đang tìm một chút xanh nào?"/><button aria-label="Tìm kiếm" type="submit">Tìm</button></form><Link className="ps-help" href="/lien-he">Cần một gợi ý?<b>Để chúng mình giúp bạn ↗</b></Link><Link className="ps-bag" href="/gio-hang" aria-label={'Giỏ hàng, '+count+' sản phẩm'}><Icon name="bag"/><span>{count}</span></Link></div><nav className="ps-nav ps-wrap" aria-label="Điều hướng chính"><button className="ps-categories" aria-expanded={rail} onClick={()=>{setRail(!rail);setOpen('')}}><Icon name="menu"/>Danh mục sản phẩm<Icon name="down"/></button><div className="ps-navlinks">{collections.slice(0,4).map(c=><div key={c.id} className="ps-navitem"><button aria-expanded={!rail&&open===c.id} aria-controls={'menu-'+c.id} onClick={()=>{setRail(false);setOpen(open===c.id?'':c.id)}}>{c.label}<Icon name="down" size={14}/></button>{!rail&&open===c.id&&<div id={'menu-'+c.id} className="ps-mega"><Link className="ps-menu-intro" href={c.href} onClick={()=>setOpen('')}><img src={c.image} alt=""/><b>{c.intro}</b><span>Khám phá bộ sưu tập →</span></Link>{c.groups.map(g=><div key={g.title}><strong>{g.title}</strong>{g.items.map(i=><Link key={i} href={collectionItemHref(c,i)} onClick={()=>setOpen('')}>{i}</Link>)}</div>)}</div>}</div>)}</div><Link className="ps-sale-link" href="/#flash-sale"><Icon name="bolt" size={16}/>Flash sale</Link>{rail&&<div className="ps-rail">{collections.map(c=><div key={c.id}><button aria-expanded={open===c.id} onClick={()=>setOpen(open===c.id?'':c.id)}><Icon name={c.icon}/>{c.label}<Icon name="right" size={16}/></button>{open===c.id&&<div className="ps-flyout"><Link href={c.href} onClick={()=>setRail(false)}><b>{c.intro} →</b></Link>{c.groups.map(g=><div key={g.title}><strong>{g.title}</strong>{g.items.map(i=><Link key={i} href={collectionItemHref(c,i)} onClick={()=>setRail(false)}>{i}</Link>)}</div>)}</div>}</div>)}</div>}</nav></header>}
