 'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
const slides=[
 {image:'/assets/images/hero.jpg',alt:'Không gian xanh ngập nắng với cây nội thất và chậu đất nung',eyebrow:'01 / KHÔNG GIAN SỐNG XANH',title:'Mang thiên nhiên',accent:'về phía bạn.',description:'Cây xanh, hoa tươi và những góc bình yên — dành cho ngôi nhà và người bạn thương.',href:'/cay-canh',cta:'Khám phá cây xanh'},
 {image:'/assets/images/cat-services.jpg',alt:'Khu vườn xanh được chăm sóc giữa cảnh quan thiên nhiên',eyebrow:'02 / THIẾT KẾ & THI CÔNG',title:'Từ ý tưởng xanh,',accent:'đến khu vườn thật.',description:'Cùng tạo nên cảnh quan hài hòa cho sân vườn, biệt thự và không gian làm việc.',href:'/dich-vu',cta:'Khám phá dịch vụ'},
 {image:'/assets/images/cat-outdoor.jpg',alt:'Khu vườn hoa nhiều màu sắc trong ánh sáng tự nhiên',eyebrow:'03 / MÓN QUÀ TỪ THIÊN NHIÊN',title:'Trao một chút xanh,',accent:'gửi ngàn yêu thương.',description:'Hoa, cây và Gift voucher — để người nhận tự chọn điều khiến mình mỉm cười.',href:'/gift-voucher',cta:'Khám phá Gift voucher'}
];
export function HeroSlider(){const [active,setActive]=useState(0);const [paused,setPaused]=useState(false);const [hovered,setHovered]=useState(false);const [focused,setFocused]=useState(false);const [reduced,setReduced]=useState(true);
useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduced(media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync)},[]);
useEffect(()=>{if(paused||hovered||focused||reduced)return;const timer=setInterval(()=>setActive(i=>(i+1)%slides.length),6500);return()=>clearInterval(timer)},[paused,hovered,focused,reduced]);const s=slides[active];
return <section className="dn-hero" aria-label="Bộ sưu tập Đà Lạt New" aria-roledescription="carousel" onPointerEnter={e=>{if(e.pointerType==='mouse')setHovered(true)}} onPointerLeave={()=>setHovered(false)} onFocusCapture={()=>setFocused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setFocused(false)}}><div className="dn-slides" aria-hidden="true">{slides.map((item,i)=><img key={item.image} className={i===active?'is-active':''} src={item.image} alt="" width="1400" height="900" fetchPriority={i===0?'high':'low'}/>)}</div><div className="dn-shade"/><div className="dn-hero-inner ps-wrap"><div className="dn-brand"><span>CÔNG TY SẢN XUẤT THƯƠNG MẠI DỊCH VỤ</span><strong>Đà Lạt New</strong></div><div className="dn-slide-copy" role="group" aria-roledescription="slide" aria-label={(active+1)+' / 3 · '+s.alt}><span className="ps-eyebrow">{s.eyebrow}</span><h1>{s.title}<br/><em>{s.accent}</em></h1><p>{s.description}</p><div className="ps-actions"><Link className="ps-button dn-hero-cta" href={s.href}>{s.cta} ↗</Link><Link className="dn-secondary" href="/lien-he">Tư vấn cùng Đà Lạt New →</Link></div></div><div className="dn-slider-controls"><div className="dn-dots" aria-label="Chọn ảnh trình chiếu">{slides.map((_,i)=><button key={i} aria-label={'Xem ảnh '+(i+1)} aria-pressed={active===i} onClick={()=>setActive(i)}><span/>{String(i+1).padStart(2,'0')}</button>)}</div><div className="dn-arrows"><button aria-label="Ảnh trước" onClick={()=>setActive((active+2)%3)}>←</button><button aria-label={paused||reduced?'Chạy trình chiếu':'Tạm dừng trình chiếu'} onClick={()=>{setReduced(false);setPaused(!(paused||reduced))}}>{paused||reduced?'▶':'Ⅱ'}</button><button aria-label="Ảnh tiếp theo" onClick={()=>setActive((active+1)%3)}>→</button></div></div></div><span className="dn-hero-signature">NATURE. SPACE. EMOTION.</span></section>}
